[package]
name = "cel-interpreter"
description = "An interpreter for the Common Expression Language (CEL)"
repository = "https://github.com/orf/cel-rust"
version = "0.1.3-alpha.0"
authors = ["Tom Forbes <tom@tomforb.es>"]
edition = "2018"
license = "MIT"
categories = ["interpreter", "cel"]

[dependencies]
cel-parser = { path = "../parser"}
thiserror = "1.0.22"
regex = "1.8.1"
lazy_static = "1.4.0"

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "runtime"
harness = false
